#!/usr/bin/env node bin/coffee
fs = require 'fs'
path = require 'path'

CJSEverywhere = require 'commonjs-everywhere'
escodegen = require 'escodegen'
esmangle = require 'esmangle'

root = __dirname

ast = CJSEverywhere.cjsifySync './src/browser.coffee', root,
  aliases:
    '/src/parser.coffee': '/lib/parser.js'
  export: 'CoffeeScript'
  ignoreMissing: yes
  verbose: yes

ast = esmangle.mangle (esmangle.optimize ast), destructive: yes

{code, map} = escodegen.generate ast,
  sourceMapRoot: path.resolve root
  sourceMapWithCode: yes
  sourceMap: yes

fs.writeFile 'dist/coffee-script-redux.min.js', "#{code}\n/*\n//@ sourceMappingURL=coffee-script-redux.min.js.map\n*/"
fs.writeFile 'dist/coffee-script-redux.min.js.map', map
