// Generated by CoffeeScript 2.0.0-beta8
var child_process, coffeeBinary, CoffeeScript, fork, fs, path, runModule;
child_process = require('child_process');
fs = require('fs');
path = require('path');
CoffeeScript = require('./module');
runModule = require('./run').runModule;
module.exports = !(null != require.extensions['.coffee']);
if (null != require.extensions['.coffee'])
  require.extensions['.coffee'];
else
  require.extensions['.coffee'] = function (module, filename) {
    var csAst, input, js, jsAst;
    input = fs.readFileSync(filename, 'utf8');
    csAst = CoffeeScript.parse(input, { raw: true });
    jsAst = CoffeeScript.compile(csAst);
    js = CoffeeScript.js(jsAst);
    return runModule(module, js, jsAst, filename);
  };
if (null != require.extensions['.litcoffee'])
  require.extensions['.litcoffee'];
else
  require.extensions['.litcoffee'] = function (module, filename) {
    var csAst, input, js, jsAst;
    input = fs.readFileSync(filename, 'utf8');
    csAst = CoffeeScript.parse(input, {
      raw: true,
      literate: true
    });
    jsAst = CoffeeScript.compile(csAst);
    js = CoffeeScript.js(jsAst);
    return runModule(module, js, jsAst, filename);
  };
fork = child_process.fork;
if (!fork.coffeePatched) {
  coffeeBinary = path.resolve('bin', 'coffee');
  child_process.fork = function (file, args, options) {
    if (null == args)
      args = [];
    if (null == options)
      options = {};
    if (in$(path.extname(file), [
        '.coffee',
        '.litcoffee'
      ])) {
      if (!Array.isArray(args)) {
        args = [];
        options = args || {};
      }
      options.execPath || (options.execPath = coffeeBinary);
    }
    return fork(file, args, options);
  };
  child_process.fork.coffeePatched = true;
}
function in$(member, list) {
  for (var i = 0, length = list.length; i < length; ++i)
    if (i in list && list[i] === member)
      return true;
  return false;
}
