// Generated by TypedCoffeeScript 0.8.5
var pj, render, Reporter, TypeError;
pj = function () {
  try {
    return require('prettyjson');
  } catch (e$) {
    return;
  }
}.call(this);
render = function (obj) {
  if (null != pj)
    return pj.render(obj);
};
TypeError = require('./type-helpers').TypeError;
Reporter = function () {
  function Reporter() {
    var instance$;
    instance$ = this;
    this.add_warning = function (a, b) {
      return Reporter.prototype.add_warning.apply(instance$, arguments);
    };
    this.clean = function () {
      return Reporter.prototype.clean.apply(instance$, arguments);
    };
    this.add_error = function (a, b) {
      return Reporter.prototype.add_error.apply(instance$, arguments);
    };
    this.errors = [];
    this.warnings = [];
  }
  Reporter.prototype.has_errors = function () {
    return this.errors.length > 0;
  };
  Reporter.prototype.has_warnings = function () {
    return this.warnings.length > 0;
  };
  Reporter.prototype.report = function () {
    var errors;
    errors = this.errors.map(function (param$) {
      var cache$, node, text;
      {
        cache$ = param$;
        node = cache$[0];
        text = cache$[1];
      }
      return '' + text + '\n  at | ' + node.raw + '';
    });
    return '[Error]\n' + errors.join('\n') + '';
  };
  Reporter.prototype.add_error = function (node, text) {
    return this.errors.push([
      node,
      text
    ]);
  };
  Reporter.prototype.clean = function () {
    return this.errors = [];
  };
  Reporter.prototype.add_warning = function (node) {
    var ws;
    ws = arguments.length > 1 ? [].slice.call(arguments, 1) : [];
    return this.warnings.push([
      node,
      ws.join('')
    ]);
  };
  Reporter.prototype.dump = function (node, prefix) {
    var key, next, val;
    if (null == prefix)
      prefix = '';
    console.log(prefix + ('[' + node.name + ']'));
    for (key in node._vars) {
      val = node._vars[key];
      console.log(prefix, ' +', key, '::', JSON.stringify(val));
    }
    return function (accum$) {
      for (var i$ = 0, length$ = node.nodes.length; i$ < length$; ++i$) {
        next = node.nodes[i$];
        accum$.push(this.dump(next, prefix + '  '));
      }
      return accum$;
    }.call(this, []);
  };
  return Reporter;
}();
module.exports = new Reporter;
