// Generated by CoffeeScript 1.3.3
(function() {
  var concat, declarationsFor, foldl, foldl1, name, node, _ref, _ref1;

  _ref = require('./helpers'), concat = _ref.concat, foldl = _ref.foldl, foldl1 = _ref.foldl1;

  _ref1 = require('./nodes');
  for (name in _ref1) {
    node = _ref1[name];
    global[name in global ? "CS" + name : name] = node;
  }

  declarationsFor = function(vars) {
    return foldl((new Undefined).g(), vars, function(expr, v) {
      return (new AssignOp(v, expr)).g();
    });
  };

  this.Optimiser = (function() {
    var defaultRules;

    defaultRules = [
      [
        Block, function(inScope, ancestors) {
          var canDropLast, stmts, _ref2,
            _this = this;
          canDropLast = (_ref2 = ancestors[0]) != null ? _ref2["instanceof"](Program, Class) : void 0;
          stmts = concat((function() {
            var i, s, _i, _len, _ref3, _results;
            _ref3 = _this.statements;
            _results = [];
            for (i = _i = 0, _len = _ref3.length; _i < _len; i = ++_i) {
              s = _ref3[i];
              switch (false) {
                case !((!s.mayHaveSideEffects(inScope)) && (canDropLast || i + 1 !== _this.statements.length)):
                  _results.push([declarationsFor(s.envEnrichments())]);
                  break;
                case !s["instanceof"](Block):
                  _results.push(s.statements);
                  break;
                case !s["instanceof"](SeqOp):
                  _results.push([s.left, s.right]);
                  break;
                default:
                  _results.push([s]);
              }
            }
            return _results;
          })());
          switch (stmts.length) {
            case 0:
              return (new Undefined).g();
            case 1:
              return stmts[0];
            default:
              return foldl1(stmts, function(expr, s) {
                return new SeqOp(expr, s);
              });
          }
        }
      ], [
        SeqOp, function(inScope) {
          if (this.left.mayHaveSideEffects(inScope)) {
            return this;
          }
          if ((this.right["instanceof"](Identifier)) && this.right.data === 'eval') {
            if ((this.left["instanceof"](Int)) && this.left.data === 0) {
              return this;
            }
            return new SeqOp((new Int(0)).g(), this.right);
          }
          return this.right;
        }
      ], [
        While, function(inScope) {
          if (this.condition.isFalsey()) {
            if (this.condition.mayHaveSideEffects(inScope)) {
              return this.condition;
            } else {
              if (typeof block !== "undefined" && block !== null) {
                return declarationsFor(this.block.envEnrichments());
              } else {
                return (new Undefined).g();
              }
            }
          }
          if (this.condition.isTruthy()) {
            if (!this.condition.mayHaveSideEffects(inScope)) {
              if (this.block == null) {
                return (new Undefined).g();
              }
              if (this instanceof Loop) {
                return this;
              }
              return (new Loop(this.block)).g();
            }
          }
          return this;
        }
      ], [
        Conditional, function(inScope) {
          var block, removedBlock;
          if (this.condition.isFalsey()) {
            block = this.elseBlock;
            removedBlock = this.block;
          } else if (this.condition.isTruthy()) {
            block = this.block;
            removedBlock = this.elseBlock;
          } else {
            return this;
          }
          block = Block.wrap(block);
          if (removedBlock != null) {
            block.statements.unshift(declarationsFor(removedBlock.envEnrichments()));
          }
          if (this.condition.mayHaveSideEffects(inScope)) {
            this.condition.unshift(block);
          }
          return block;
        }
      ], [
        ForIn, function() {
          if (!((this.expr["instanceof"](ArrayInitialiser)) && this.expr.members.length === 0)) {
            return this;
          }
          return new SeqOp(declarationsFor(this.envEnrichments()), (new ArrayInitialiser([])).g());
        }
      ], [
        ForOf, function() {
          if (!((this.expr["instanceof"](ObjectInitialiser)) && this.expr.isOwn && this.expr.members.length === 0)) {
            return this;
          }
          return new SeqOp(declarationsFor(this.envEnrichments()), (new ArrayInitialiser([])).g());
        }
      ], [
        LogicalNotOp, function() {
          switch (this.expr.className) {
            case Int.prototype.className:
            case Float.prototype.className:
            case String.prototype.className:
            case Bool.prototype.className:
              return (new Bool(!this.expr.data)).g();
            case Function.prototype.className:
            case BoundFunction.prototype.className:
              return (new Bool(false)).g();
            case Null.prototype.className:
            case Undefined.prototype.className:
              return (new Bool(true)).g();
            case ArrayInitialiser.prototype.className:
            case ObjectInitialiser.prototype.className:
              if (this.expr.mayHaveSideEffects()) {
                return this;
              } else {
                return new SeqOp(declarationsFor(this.expr.envEnrichments()), (new Bool(false)).g());
              }
              break;
            case LogicalNotOp.prototype.className:
              if (this.expr.expr["instanceof"](LogicalNotOp)) {
                return this.expr.expr;
              } else {
                return this;
              }
              break;
            default:
              return this;
          }
        }
      ], [
        TypeofOp, function() {
          switch (this.expr.className) {
            case Int.prototype.className:
            case Float.prototype.className:
            case UnaryNegateOp.prototype.className:
            case UnaryPlusOp.prototype.className:
              return (new String('number')).g();
            case String.prototype.className:
              return (new String('string')).g();
            case Function.prototype.className:
            case BoundFunction.prototype.className:
              return (new String('function')).g();
            case Undefined.prototype.className:
              return (new String('undefined')).g();
            default:
              return this;
          }
        }
      ]
    ];

    function Optimiser() {
      var ctor, handler, _i, _len, _ref2;
      this.rules = {};
      for (_i = 0, _len = defaultRules.length; _i < _len; _i++) {
        _ref2 = defaultRules[_i], ctor = _ref2[0], handler = _ref2[1];
        this.addRule(ctor.prototype.className, handler);
      }
    }

    Optimiser.prototype.addRule = function(ctor, handler) {
      var _base, _ref2;
      ((_ref2 = (_base = this.rules)[ctor]) != null ? _ref2 : _base[ctor] = []).push(handler);
    };

    Optimiser.prototype.optimise = function(ast) {
      var rules;
      rules = this.rules;
      return ast.walk(function(inScope, ancestry) {
        var memo, rule, _i, _len, _ref2, _ref3;
        memo = this;
        _ref3 = (_ref2 = rules[this.className]) != null ? _ref2 : [];
        for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
          rule = _ref3[_i];
          memo = rule.call(memo, inScope, ancestry);
        }
        return memo;
      });
    };

    return Optimiser;

  })();

}).call(this);
